### ISSUE TITLE
[Question] Blog

### ISSUE THREAD

**Issue by AkiaCode** [kimain050401/kimain050401.github.io#1]
확인해 보니 블로그가 두 개인데 기술 블로그는 `https://aineraser.tistory.com/` 이고 일기장은 `https://kimain050401.github.io/blog/` 인 것이 확실하나요?

**Comment by kimain050401** [comment]
Github 블로그(kimain050401.github.com/blog)는 조만간 삭제 예정입니다!
티스토리(aineraser.tistory.com)에서 일기장과 기술 모두 확인하실 수 있습니다 :)
Github 프로필(kimain050401.github.com)은 그대로 유지할 예정입니다!

**Comment by kimain050401** [comment]
>  확인해 보니 블로그가 두 개인데 기술 블로그는 `https://aineraser.tistory.com/` 이고 일기장은 `https://kimain050401.github.io/blog/` 인 것이 확실하나요?

Github 블로그(kimain050401.github.com/blog)는 조만간 삭제 예정입니다!
티스토리(aineraser.tistory.com)에서 일기장과 기술 모두 확인하실 수 있습니다 :)
Github 프로필(kimain050401.github.com)은 그대로 유지할 예정입니다!

**Comment by AkiaCode** [comment]
> aineraser.tistory.com)

![image](https://user-images.githubusercontent.com/71239005/103786247-907b4b00-507f-11eb-8be2-4c0274eaf701.png)

그럼 이러한 글도 이동 되는 건가요?

**Comment by kimain050401** [comment]
> ![image](https://user-images.githubusercontent.com/71239005/103786247-907b4b00-507f-11eb-8be2-4c0274eaf701.png)
> 
> 
> 
> 그럼 이러한 글도 이동 되는 건가요?

아뇨아뇨 그 글은 지울 예정입니다! 아마 티스토리 블로그에 새로 쓸거같습니다 ;)

**Comment by AkiaCode** [comment]
> > ![image](https://user-images.githubusercontent.com/71239005/103786247-907b4b00-507f-11eb-8be2-4c0274eaf701.png)
> > 그럼 이러한 글도 이동 되는 건가요?
> 
> 아뇨아뇨 그 글은 지울 예정입니다! 아마 티스토리 블로그에 새로 쓸거같습니다 ;)

네넵, 알겠습니다 그리고 언제나 응원하겠습니다!
그럼 이제 이슈를 닫겠습니다
